# Generated by Django 4.1 on 2022-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_end_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="end_data",),
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date expired"
            ),
        ),
    ]
