# Generated by Django 4.1 on 2022-09-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_remove_choice_votes_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote", name="votes", field=models.IntegerField(default=0),
        ),
    ]
